// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Chair
	CreateChair(ctx context.Context, arg CreateChairParams) (Chair, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Wardrobe
	CreateWardrobe(ctx context.Context, arg CreateWardrobeParams) (Wardrobe, error)
	DeleteChair(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteUserByEmail(ctx context.Context, email string) error
	DeleteWardrobe(ctx context.Context, id pgtype.UUID) error
	GetChair(ctx context.Context, id pgtype.UUID) (Chair, error)
	GetChairByModel(ctx context.Context, model ChairModel) (Chair, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWardrobe(ctx context.Context, id pgtype.UUID) (Wardrobe, error)
	GetWardrobeByModel(ctx context.Context, model WardrobeModel) (Wardrobe, error)
	// Warehouse
	GetWarhouse(ctx context.Context, productModel string) (Warehouse, error)
	ListChairs(ctx context.Context, arg ListChairsParams) ([]Chair, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWardrobe(ctx context.Context, arg ListWardrobeParams) ([]Wardrobe, error)
	ListWarehouse(ctx context.Context) ([]Warehouse, error)
	UpdateChair(ctx context.Context, arg UpdateChairParams) (Chair, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWardrobe(ctx context.Context, arg UpdateWardrobeParams) (Wardrobe, error)
	UpdateWarehouseQuantity(ctx context.Context, arg UpdateWarehouseQuantityParams) error
}

var _ Querier = (*Queries)(nil)
