// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nurkenti/furnitureShop/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	sqlc "github.com/nurkenti/furnitureShop/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateChair mocks base method.
func (m *MockStore) CreateChair(arg0 context.Context, arg1 sqlc.CreateChairParams) (sqlc.Chair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChair", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Chair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChair indicates an expected call of CreateChair.
func (mr *MockStoreMockRecorder) CreateChair(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChair", reflect.TypeOf((*MockStore)(nil).CreateChair), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 sqlc.CreateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateWardrobe mocks base method.
func (m *MockStore) CreateWardrobe(arg0 context.Context, arg1 sqlc.CreateWardrobeParams) (sqlc.Wardrobe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWardrobe", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Wardrobe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWardrobe indicates an expected call of CreateWardrobe.
func (mr *MockStoreMockRecorder) CreateWardrobe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWardrobe", reflect.TypeOf((*MockStore)(nil).CreateWardrobe), arg0, arg1)
}

// DeleteChair mocks base method.
func (m *MockStore) DeleteChair(arg0 context.Context, arg1 pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChair", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChair indicates an expected call of DeleteChair.
func (mr *MockStoreMockRecorder) DeleteChair(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChair", reflect.TypeOf((*MockStore)(nil).DeleteChair), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// DeleteUserByEmail mocks base method.
func (m *MockStore) DeleteUserByEmail(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByEmail indicates an expected call of DeleteUserByEmail.
func (mr *MockStoreMockRecorder) DeleteUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByEmail", reflect.TypeOf((*MockStore)(nil).DeleteUserByEmail), arg0, arg1)
}

// DeleteWardrobe mocks base method.
func (m *MockStore) DeleteWardrobe(arg0 context.Context, arg1 pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWardrobe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWardrobe indicates an expected call of DeleteWardrobe.
func (mr *MockStoreMockRecorder) DeleteWardrobe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWardrobe", reflect.TypeOf((*MockStore)(nil).DeleteWardrobe), arg0, arg1)
}

// GetChair mocks base method.
func (m *MockStore) GetChair(arg0 context.Context, arg1 pgtype.UUID) (sqlc.Chair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChair", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Chair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChair indicates an expected call of GetChair.
func (mr *MockStoreMockRecorder) GetChair(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChair", reflect.TypeOf((*MockStore)(nil).GetChair), arg0, arg1)
}

// GetChairByModel mocks base method.
func (m *MockStore) GetChairByModel(arg0 context.Context, arg1 sqlc.ChairModel) (sqlc.Chair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChairByModel", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Chair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChairByModel indicates an expected call of GetChairByModel.
func (mr *MockStoreMockRecorder) GetChairByModel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChairByModel", reflect.TypeOf((*MockStore)(nil).GetChairByModel), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(arg0 context.Context, arg1 pgtype.UUID) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), arg0, arg1)
}

// GetWardrobe mocks base method.
func (m *MockStore) GetWardrobe(arg0 context.Context, arg1 pgtype.UUID) (sqlc.Wardrobe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWardrobe", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Wardrobe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWardrobe indicates an expected call of GetWardrobe.
func (mr *MockStoreMockRecorder) GetWardrobe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWardrobe", reflect.TypeOf((*MockStore)(nil).GetWardrobe), arg0, arg1)
}

// GetWardrobeByModel mocks base method.
func (m *MockStore) GetWardrobeByModel(arg0 context.Context, arg1 sqlc.WardrobeModel) (sqlc.Wardrobe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWardrobeByModel", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Wardrobe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWardrobeByModel indicates an expected call of GetWardrobeByModel.
func (mr *MockStoreMockRecorder) GetWardrobeByModel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWardrobeByModel", reflect.TypeOf((*MockStore)(nil).GetWardrobeByModel), arg0, arg1)
}

// GetWarhouse mocks base method.
func (m *MockStore) GetWarhouse(arg0 context.Context, arg1 string) (sqlc.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarhouse", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarhouse indicates an expected call of GetWarhouse.
func (mr *MockStoreMockRecorder) GetWarhouse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarhouse", reflect.TypeOf((*MockStore)(nil).GetWarhouse), arg0, arg1)
}

// ListChairs mocks base method.
func (m *MockStore) ListChairs(arg0 context.Context, arg1 sqlc.ListChairsParams) ([]sqlc.Chair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChairs", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Chair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChairs indicates an expected call of ListChairs.
func (mr *MockStoreMockRecorder) ListChairs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChairs", reflect.TypeOf((*MockStore)(nil).ListChairs), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(arg0 context.Context, arg1 sqlc.ListUsersParams) ([]sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), arg0, arg1)
}

// ListWardrobe mocks base method.
func (m *MockStore) ListWardrobe(arg0 context.Context, arg1 sqlc.ListWardrobeParams) ([]sqlc.Wardrobe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWardrobe", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.Wardrobe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWardrobe indicates an expected call of ListWardrobe.
func (mr *MockStoreMockRecorder) ListWardrobe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWardrobe", reflect.TypeOf((*MockStore)(nil).ListWardrobe), arg0, arg1)
}

// ListWarehouse mocks base method.
func (m *MockStore) ListWarehouse(arg0 context.Context) ([]sqlc.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWarehouse", arg0)
	ret0, _ := ret[0].([]sqlc.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWarehouse indicates an expected call of ListWarehouse.
func (mr *MockStoreMockRecorder) ListWarehouse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWarehouse", reflect.TypeOf((*MockStore)(nil).ListWarehouse), arg0)
}

// UpdateChair mocks base method.
func (m *MockStore) UpdateChair(arg0 context.Context, arg1 sqlc.UpdateChairParams) (sqlc.Chair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChair", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Chair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChair indicates an expected call of UpdateChair.
func (mr *MockStoreMockRecorder) UpdateChair(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChair", reflect.TypeOf((*MockStore)(nil).UpdateChair), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 sqlc.UpdateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateWardrobe mocks base method.
func (m *MockStore) UpdateWardrobe(arg0 context.Context, arg1 sqlc.UpdateWardrobeParams) (sqlc.Wardrobe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWardrobe", arg0, arg1)
	ret0, _ := ret[0].(sqlc.Wardrobe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWardrobe indicates an expected call of UpdateWardrobe.
func (mr *MockStoreMockRecorder) UpdateWardrobe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWardrobe", reflect.TypeOf((*MockStore)(nil).UpdateWardrobe), arg0, arg1)
}

// UpdateWarehouseQuantity mocks base method.
func (m *MockStore) UpdateWarehouseQuantity(arg0 context.Context, arg1 sqlc.UpdateWarehouseQuantityParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWarehouseQuantity", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWarehouseQuantity indicates an expected call of UpdateWarehouseQuantity.
func (mr *MockStoreMockRecorder) UpdateWarehouseQuantity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWarehouseQuantity", reflect.TypeOf((*MockStore)(nil).UpdateWarehouseQuantity), arg0, arg1)
}
